				<div id="main_col"><!-- main column -->
                    
                    
                    </div><!-- end main column -->
                    
                <div id="side_col"><!-- side solumn -->
                    
                    
                    
                </div><!-- end side column -->
                
                
                </div> <!-- end content -->
       
            
              </div> <!-- end container -->
        
           		
      	<div id="footer"><!-- footer -->
                
        	<p class="footy">|| All images Copyright &copy; Chen Chen 2013 || Contact me at: <a href="mailto:chen@chen2illustrations.com" title="chen chen illustrations" id="cmail">chen@chen2illustrations.com</a></p>
                
        </div> <!-- end footer --> 
      
      <!-- the part that makes the parallax work -->
      
      	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js"></script>
		<script src="js/jquery.parallax.js"></script>
		<script type="text/javascript">
		
			jQuery(document).ready(function(){
				
			jQuery('#parallax .parallax-layer')
			
			
			.parallax({
				  mouseport: jQuery('#parallax')
				  
				});
			  });
		</script>